### ISSUE TITLE
xmlns URLs geven 404 terug

### ISSUE THREAD

**Issue by joepio** [TweedeKamerDerStaten-Generaal/Open-Data-Portaal#28]
De `xmlns` en `xmlns:tk` URLs uit de SyncFeed geven momenteel 404's terug:

`http://www.tweedekamer.nl/xsd/tkData/v1-0`  

Deze zouden vermoedelijk naar de [XSD beschrijvingen](https://gegevensmagazijn.tweedekamer.nl/Contract/tkdata-v1-0.xsd) moeten verwijzen.

**Comment by DanielVanHilten** [comment]
Beste Joep, deze verwijzingen zijn namespaces, de exacte technische reden waarom je hier niets vindt zal ik nog even nazoeken. Indien je de XSD's wilt hebben dan kan dit via:
`view-source:https://gegevensmagazijn.tweedekamer.nl/Contract/tkData-v1-0.xsd`

Ik zal dit tevens nog toevoegen aan de documentatie. Goed punt!
