### ISSUE TITLE
Geen valide XML content

### ISSUE THREAD

**Issue by alphons** [TweedeKamerDerStaten-Generaal/Open-Data-Portaal#90]
`<content type="application/xml">
	<ns1:verslag xmlns:ns1="http://www.tweedekamer.nl/xsd/tkData/v1-0" id="abc" ns1:verwijderd="false" ns1:bijgewerkt="2020-03-07T21:48:20.0603012+01:00" ns1:contentType="text/xml" ns1:contentLength="123">
		<ns1:vergadering xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns1:referentieLiteral" ref="def"/>
		<ns1:soort>Tussenpublicatie</ns1:soort>
		<ns1:status>Ongecorrigeerd</ns1:status>
	</ns1:verslag>
</content>`

xsi:type="ns1:referentieLiteral"  type referentieLiteral niet herkent namespace http://www.tweedekamer.nl/xsd/tkData/v1-0

Is er wel een external XSD ?

**Comment by OpenDataPortaal** [comment]
We waren nog bezig met het beschikbaar stellen van de XSD's, maar we hebben er wat vaart achter gezet. Op de onderstaande pagina is een overzicht te vinden van de XSD's:

https://opendata.tweedekamer.nl/documentatie/xsd-xml-schema-definition-standaard  

Een verwijzing naar deze pagina is toegevoegd aan de [documentatiepagina over het informatiemodel](https://opendata.tweedekamer.nl/documentatie/informatiemodel).
